language: python
cache:
    directories:
        - "$HOME/google-cloud-sdk/"

env:
    global:
        - GAE_PYTHONPATH=${HOME}/.cache/google_appengine
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH}
    matrix:
        - RUN_TESTS=true
        - RUN_PYLINT=true

install:
    - "./ci/install.sh"

script:
    - "./ci/run_tests.sh"
    - "./ci/run_pylint.sh"

after_success:
    - "./ci/deploy.sh"
