runtime: python27
api_version: 1
threadsafe: yes
service: default

handlers:
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /assets/(.*)
  static_files: cookomatic_web/assets/\1
  upload: cookomatic_web/assets/.*

- url: /.*
  script: cookomatic_web.http_handler.APP
  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
